### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by bonanza** [35niavlys/dokuwiki-plugin-amcharts#4]
In action.php the depreciated funtion split() is used (see http://php.net/manual/en/function.split.php). With PHP 7 the plugin is therefore not working and produces the following PHP error:
`PHP Fatal error:  Uncaught Error: Call to undefined function split() in /srv/www/htdocs/dokuwiki/lib/plugins/amcharts/action.php:42`
This can be fixed easily by using preg_split() (http://php.net/manual/en/function.preg-split.php) instead.

**Comment by 35niavlys** [comment]
Hi, it's updated, thank you
