### ISSUE TITLE
gantt charts don't render

### ISSUE THREAD

**Issue by iancustoica** [35niavlys/dokuwiki-plugin-amcharts#6]
Hi,

Are  gantt charts supposed to work? I tried the two examples from amcharts but they don't seem to work. I was wandering if this is the same for everyone or just for me (i.e. I am doing something wrong).

This is what I am talking about:

[https://www.amcharts.com/demos/gantt-chart/](url)
[https://www.amcharts.com/demos/gantt-chart-dates/](url)

and this is a very basic simple example that should but doesn't work:

`<amchart>
{
  "type": "gantt",
  "categoryField": "category",
  "segmentsField": "segments",
  "colorField": "color",
  "startDateField": "start",
  "endDateField": "end",
  "dataProvider": [ {
    "category": "Module #1",
    "segments": [ {
      "start": "2016-01-01",
      "end": "2016-01-14",
      "color": "#b9783f",
      "task": "Gathering requirements"
    } ]
  } ]
}
</amchart>`

**Comment by 35niavlys** [comment]
Hi, 

In fact the problem come from the order of the imported js files :)
I updated the default conf : https://github.com/35niavlys/dokuwiki-plugin-amcharts/commit/8a06438ab630783bd67dc25cd9be82fad8998885
